---
title: "Model evaluation"
author: "Jari Turkia"
date: "6/24/2019"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra) # for good looking tables

knitr::opts_chunk$set(echo = TRUE, fig.align="center")

# this allows using tikz rendering for plots with "dev=tikz"
knit_hooks$set(plot = function(x, options) {
  if ('tikz' %in% options$dev && !options$external) {
    hook_plot_tex(x, options)
  } else hook_plot_md(x, options)
})

# Fix seed for random number generator for getting consistent results in kmeans etc.
fixed_seed <- 678

# Load common MEBN package
source("mebn/MEBN.r")
```

```{r data_loading, echo=FALSE, message=FALSE}

# Read the data description
datadesc <- read.csv(file="Data description.csv", header = TRUE, sep = ";")

# Read the actual data matching the description
sysdimet <- read.csv(file="data/SYSDIMET_diet.csv", sep=";", dec=",")

# Define how to iterate through the graph
assumedpredictors <- datadesc[datadesc$Order==100,]    
assumedtargets <- datadesc[datadesc$Order==200,] 
```

```{r, typical_effects_figure, fig.height = 8, fig.width = 10, echo=FALSE, fig.align = "center", message=FALSE, warning=FALSE, cache=FALSE}
source("mebn/MEBN.r")
require(igraph)
sysdimet_gamma_ar1 <- read_graph("sysdimet_gamma_ar1.graphml", "graphml")
graph_layout <- mebn.plot_typical_effects(sysdimet_gamma_ar1, 20)
```

```{r}
#install.packages("shinystan")
library(bayesplot)
library(rstan)

m <- mebn.get_localfit("BLMM_gamma/ar1_rhs/no_holdout/fshdl")
posterior <- as.array(m)

mcmc_areas_ridges(posterior, regex_pars = "beta") +
  ggplot2::ggtitle("Effects that are either typically significant or have high variance between persons")
```


```{r}
library(dplyr)
library(tidyr)
library(kableExtra)

true_values <- sysdimet[c("SUBJECT_ID", "WEEK", as.vector(assumedtargets$Name))]

get_true_response <- function(holdout_number) {
  
  #holdout_subject <- sprintf("S%02d", holdout_number)
  holdout_subject <- levels(sysdimet$SUBJECT_ID)[holdout_number]
  
  true_response <- true_values %>%
    filter(SUBJECT_ID == holdout_subject) %>%
    select(as.vector(assumedtargets$Name)) %>%
    t %>%
    as.matrix
  
  colnames(true_response) <- c(0,4,8,12)
  return(true_response)
}

get_pred_response <- function(localfit_directory) {

  pred_response <- NULL
  
  for (targetname in assumedtargets$Name)
  {
    print(targetname)
    target_blmm <- mebn.get_localfit(paste0(localfit_directory,targetname))
    ms <- rstan::summary(target_blmm, pars=c("Y_pred"), probs=c(0.10, 0.90), na.rm = TRUE)
  
    if (is.null(pred_response))
      pred_response <- as.vector(ms$summary[1:4,c(1)])
    else
      pred_response <- rbind(pred_response, as.vector(ms$summary[1:4,c(1)]))
  }
  
  colnames(pred_response) <- c(0,4,8,12)
  rownames(pred_response) <- as.vector(assumedtargets$Name)
  
  return(pred_response)
}

get_rep_response_for_all <- function(localfit_directory) {

  rep_response <- NULL
  
  for (targetname in assumedtargets$Name)
  {
    target_blmm <- mebn.get_localfit(paste0(localfit_directory,targetname))
    ms <- rstan::summary(target_blmm, pars=c("Y_rep"), probs=c(0.10, 0.90), na.rm = TRUE)

    if (is.null(rep_response))
      rep_response <- as.vector(ms$summary[,c(1)])
    else
      rep_response <- rbind(rep_response, as.vector(ms$summary[,c(1)]))
  }

  rownames(rep_response) <- as.vector(assumedtargets$Name)
  
  return(rep_response)
}

get_rep_response <- function(rep_matrix, subject_number) {

  s <- (subject_number-1)*4 + 1
  e <- s + 3
  
  return(rep_matrix[,s:e])
}  

make_delta <- function(true_response)
{
  true_delta <- true_response
  true_delta[,4] <- true_delta[,4] - true_delta[,3]
  true_delta[,3] <- true_delta[,3] - true_delta[,2]
  true_delta[,2] <- true_delta[,2] - true_delta[,1]
  true_delta[,1] <- 0
  
  return(true_delta)
}

```
```{r}
library(loo)
target_blmm <- mebn.get_localfit("BLMM_gamma/ar1_rhs/no_holdout/fshdl")
m1<-target_blmm

m1_loglik <- extract_log_lik(m1, merge_chains = FALSE)
m1_rel_n_eff <- relative_eff(exp(m1_loglik))
m1_loo <- loo(m1_loglik, r_eff = m1_rel_n_eff, cores = 4)
m1_loo

m2 <- mebn.get_localfit("BLMM_gamma/arr1/fshdl")
m2_loglik <- extract_log_lik(m2, merge_chains = FALSE)
m2_rel_n_eff <- relative_eff(exp(m2_loglik))
m2_loo <- loo(m2_loglik, r_eff = m2_rel_n_eff, cores = 4)
m2_loo

#m1 elpd 240
```


```{r}
# Summary matrix for RHS model

summary.mat <- matrix(0, nrow=nrow(assumedtargets),ncol=4)
rownames(summary.mat) <- assumedtargets$Name
colnames(summary.mat) <- c('week 4', 'week 8', 'week 12', '12 week change')

allrep <- get_rep_response_for_all("BLMM_gamma/ar1_rhs/no_holdout/")
number_of_preds <- 0

amount_subjects <- length(levels(sysdimet$SUBJECT_ID))

for (subject_number in 1:amount_subjects)
{
  number_of_preds <- number_of_preds + 1
  
  rep_response <- get_rep_response(allrep, subject_number)
  true_response <- get_true_response(subject_number)
  
  rep_delta <- make_delta(rep_response)
  true_delta <- make_delta(true_response)
  
  sign_matrix <- sign(rep_delta) == sign(true_delta)
  avg_change <- sign(rowSums(true_response[,2:4])/3 - true_response[,1]) == sign(rowSums(rep_response[,2:4])/3 - rep_response[,1])
  
  summary.mat <- summary.mat + cbind(sign_matrix[,2:4]*1, avg_change*1)
}

percent.mat <- summary.mat/number_of_preds * 100

percent.mat <- cbind(percent.mat, rowMeans(percent.mat[,1:3]))
colnames(percent.mat) <- c('0 to 4 weeks', '4 to 8 weeks', '8 to 12 weeks', 'avg. 12 week change', 'avg. change acc.')

percent.mat <- round(percent.mat, 0)

```


```{r}
# Summary matrix for non-shrinked model

summary.mat2 <- matrix(0, nrow=nrow(assumedtargets),ncol=4)
rownames(summary.mat2) <- assumedtargets$Name
colnames(summary.mat2) <- c('week 4', 'week 8', 'week 12', '12 week change')

allrep_norhs <- get_rep_response_for_all("BLMM_gamma/ar1/")
number_of_preds <- 0

amount_subjects <- length(levels(sysdimet$SUBJECT_ID))

for (subject_number in 1:amount_subjects)
{
  number_of_preds <- number_of_preds + 1
  
  rep_response <- get_rep_response(allrep_norhs, subject_number)
  true_response <- get_true_response(subject_number)
  
  rep_delta <- make_delta(rep_response)
  true_delta <- make_delta(true_response)
  
  sign_matrix <- sign(rep_delta) == sign(true_delta)
  avg_change <- sign(rowSums(true_response[,2:4])/3 - true_response[,1]) == sign(rowSums(rep_response[,2:4])/3 - rep_response[,1])
  
  summary.mat2 <- summary.mat2 + cbind(sign_matrix[,2:4]*1, avg_change*1)
}

summary.mat2

percent.mat2 <- summary.mat2/number_of_preds * 100
percent.mat2
rowMeans(percent.mat2[,1:3])

rowMeans(percent.mat2[,1:3])

mean(rowMeans(percent.mat[,1:3]))


```


## Model evaluation summary

This visualization summarizes how accurately we can predict if blood test values raise or lower when the current level and a diet are known. This evaluates the model that uses shrinkage. TODO: 


```{r model_summary}

kable(percent.mat) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE)

kable(percent.mat, "latex", booktabs = T, caption = "Predictive accuracy percents for correct direction of change") %>%
  kable_styling(latex_options = c("striped", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE)

```

This summarizes the non-shrinked model

```{r model_summary_for_norhs}

kable(percent.mat2) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE)

```

```{r}
library(dplyr)
library(ggplot2)

true_response <- sysdimet %>% 
  filter(SUBJECT_ID == "S02") %>%
  select(fshdl, WEEK)

localfit_directory <- "BLMM_gamma/ar1_rhs/2/"
targetname <- "fshdl"
target_blmm <- mebn.get_localfit(paste0(localfit_directory,targetname))
ms <- rstan::summary(target_blmm, pars=c("Y_pred"), probs=c(0.10, 0.90), na.rm = TRUE)

pred<-as.data.frame(ms$summary[1:4,c(1)])
pred <- cbind(pred, c(0,4,8,12))
colnames(pred) <- c("pred_value", "week")

ggplot() + 
  geom_line(data=true_response, aes(x = WEEK, y = fshdl), color="green") +
  geom_line(data=pred, aes(x = week, y = pred_value), color="orange") +
  scale_x_discrete(limits=c(0,4,8,12))


```



```{r}

bigplot <- ggplot() + scale_x_discrete(limits=c(0,4,8,12))

#for (subject_number in 47:47)
#{

subject_number <- 68

  rep_response <- get_rep_response(allrep, subject_number)
  true_response <- get_true_response(subject_number)
  
  rep.df <- as.data.frame(rep_response[targetname,])
  rep.df$week <- c(0,4,8,12)  
  colnames(rep.df) <- c("response", "week")

  true.df <- as.data.frame(true_response[targetname,])
  true.df$week <- c(0,4,8,12)  
  colnames(true.df) <- c("response", "week")

  bigplot <- bigplot + 
    geom_line(data=true.df, aes(x = week, y = response), color="green") +
    geom_line(data=rep.df, aes(x = week, y = response), color="orange") 
#}

bigplot


```


